export const REDIS_CLIENT_TOKEN = 'REDIS_CLIENT';
export const REDIS_PUB_SUB_TOKEN = 'REDIS_PUB_SUB';
export const REDIS_PUB_CONFIG_TOKEN = 'REDIS_PUB_CONFIG';
export const REDIS_SUB_CONFIG_TOKEN = 'REDIS_SUB_CONFIG';
